[package]
name = "aegis-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tokio = { version = "1", features = ["sync"] }

[build-dependencies]
tauri-build = { version = "2" }
